### ISSUE TITLE
Compilation error: 'Serial1' was not declared in this scope

### ISSUE THREAD

**Issue by EvanLin-nova** [2410gura/Golf-Direction-Distance-Meter#1]
Hello, I noticed a compilation error of "Serial 1" in your Arduino code on line 230. Isn't nano only having one hard serial port? Did you input an extra "1"? How should I modify it?

こんにちは、私はあなたのarduinoコードが230行目に「Serial 1」のコンパイルエラーが発生したことを発見しました。nanoには硬いシリアルポートが1つしかないのではないでしょうか。「1」と入力して、どのように修正すればいいのでしょうか。

**Comment by PigeonPop** [comment]
Thanks for raising issue.
This code assumes you use "Arduino nano every".
Arduino nano every has 2 hardware serial.
So if you use arduino nano every, you can compile this code.


Issue頂きありがとうございます。
このコードは「Arduino nano every」を使用することを前提として作成しています。
Arduino nano everyはハードウェアシリアルを2本使用できるためです。
そのため、Arduino nano everyをご使用頂くことで、コンパイル可能になります。

**Comment by PigeonPop** [comment]
Also, this code use 1 hardware serial for displaying debug message on arduino IDE.
So this code can use on "arduino nano" by erasing code for debug message and rewrite "Serial 1" to "Serial" in line 230.

補足ですが、このコードはハードウェアシリアルの1つをarduino IDE上でデバッグメッセージを表示させるために使用しています。
そのため、デバッグ用のコードを除去し、230行目の"Serial 1" を"Serial"に書き換えれば、arduino nanoでも使用できます。
