### ISSUE TITLE
How to configure CSV files in SD card？

### ISSUE THREAD

**Issue by EvanLin-nova** [2410gura/Golf-Direction-Distance-Meter#2]
Hello, when I was looking at the configuration CSV file mentioned at this location, I didn't quite understand the geographic related vocabulary you mentioned in Japanese. My understanding is to store the longitude and latitude information of the target point inside. Can you provide an example? Thanks!
     * 1行あたり1ホール分の情報，全18行(ホール)分  
     * 1行のデータ構成：    
     *  (パー数),(左側ピン緯度),(左側ピン経度),(右側ピン緯度),(右側ピン経度)

こんにちは、私はこの位置で説明された構成csvファイルを見ているとき、あなたが日本語で言及した地理関連用語についてよく理解していません。私の理解は目標点の緯度情報を中に入れることですが、なぜ左側右側に言及したのか、例をあげてもいいですか。

**Comment by PigeonPop** [comment]
Hello.
I explain about why green exist left and right.
This is the unique culture in Japan, golf courses in Japan have 2 greens, main and sub green, and the goal green changes depending on the day.
We don't know which green is used until we play each hole.
So this code can register 2 greens in the map data CSV file in advance and switch which green to aim for during play.

こんにちは。
グリーンが左右2つ存在する理由について説明します。
これはどうやら日本独自の文化のようですが、日本のゴルフ場にはメイングリーン、サブグリーンの2つのグリーンがあり、日によってゴールとなるグリーンが変わるためです。
各ホールをプレイするまではどちらのグリーンが使われるか分からないため、あらかじめ2つのグリーンをマップデータのCSVに登録しておき、プレイ中に左右どちらのグリーンを目標とするか切り替える使い方を想定しているためこのような構成となっています。

**Comment by EvanLin-nova** [comment]
May I ask if you can upload a CSV sample file? Thank you!

csvサンプルファイルをアップロードしてもいいですか。ありがとうございます。

**Comment by PigeonPop** [comment]
I added sample CSV file.
Please check it.

サンプルCSVファイルを追加しました。
ご確認ください。
