### ISSUE TITLE
Sensor. initialize() failed to successfully initialize GPS and CPS

### ISSUE THREAD

**Issue by EvanLin-nova** [2410gura/Golf-Direction-Distance-Meter#3]
Hello, I have noticed that I am unable to successfully execute sensor. initialize() in setup() and initialize GPS and CPS. I have been troubleshooting the issue with the initialize function and feel that when calling the DFRobot_QMC5883. h library, I was not assigned a corresponding address to QMC5883. When I changed the address of i2c in the example program of DFRobot_QMC5883 to 0x0D, it was able to be successfully read. In your sample program, I did not find the i2c address. What should I do to make sensor. initialize() execute successfully?

こんにちは、私はsetup()の中でsensor.initialize()を実行することができないことを発見して、gpsとcpsを初期化することに成功することができなくて、私はずっとinitialize関数の中の問題を調べて、DFRobot _ QMC 5883.hライブラリを呼び出す時、QMC 5883に対応するアドレスを与えていないかどうかを感じて、私はDFRobot _ QMC 5883のサンプルプログラムのi 2 cのアドレスを0 x 0 Dに変えた時、読み取ることに成功することができます。あなたのサンプルプログラムでは、i 2 cアドレスは見つかりませんでしたが、sensor.initialize()を成功させるにはどうすればいいですか。

**Comment by PigeonPop** [comment]
Hello.
I was unable to reproduce the same situation.
But DFRobot_QMC5883 has a function that detects I2C address of connecting devices in function "begin()", we don't have to specify the address of QMC5883 in the ino file.
Also, when you start my code, if the following displayed on serial monitor of IDE, QMC5883 is detected correctly and is working:
isHMC_= 0
isQMC_= 1
The version of DFRobot_QMC5883.h I use is as follows:
@Version V1.0
@Date 2017-7-3

こんにちは。
当方では同様な現象を再現できませんでした。
しかし，DFRobot_QMC5883はbegin()関数でI2Cに接続されているアドレスを検知する機能があるため，inoファイル上でQMC5883のアドレスを指定する必要がありません。
また，私のコードを起動したとき, IDEのシリアルモニタ上で以下のような表示がされればQMC5883は正しく検知され，動作していると考えられます:
isHMC_= 0
isQMC_= 1
なお，当方で使用しているDFRobot_QMC5883.hのバージョンは次の通りです:
@version V1.0
@date 2017-7-3
